Include python 3.8
arthurio/fastapi-filter pull request #158
Opened 2022-10-31 08:44 UTC by 10ourto

Nice library. I need to use it with python 3.8, unfortunately can't bump python version for a while. I've included python 3.8 to library dependencies seems there is no any blocker for that.

2022-10-31 08:58 UTC, 10ourto commented
@arthurio same motivation as in https://github.com/arthurio/fastapi-filter/pull/114 but for python 3.8

2022-11-02 00:08 UTC, arthurio reviewed
Looking good, let see what the tests say...

2022-11-02 00:08 UTC, arthurio commented on pyproject.toml
> +pydantic = ">=1.9.1,<2.0.0"
Hmm we do need pydantic `>= 1.10.0` for python 3.11. 🤔 Maybe there is a way to declare that?

2022-11-02 00:23 UTC, arthurio requested changes
Can you tell me why you needed to change the pydantic requirement? Also, it does look like we need to go back to `from typing import Dict, List, ...` to support python 3.8.

2022-11-02 08:56 UTC, 10ourto commented
> Can you tell me why you needed to change the pydantic requirement? Also, it does look like we need to go back to `from typing import Dict, List, ...` to support python 3.8.

yep you right we need to fix imports for python 3.8

> pydantic

to be honest I've just downgraded it due to my project requirements, since it has some conflicts

2022-11-03 04:38 UTC, arthurio commented on pyproject.toml
> +pydantic = ">=1.9.1,<2.0.0"
Hmm that's surprising, look at https://github.com/arthurio/fastapi-filter/pull/67

2022-11-07 14:42 UTC, 10ourto commented
@arthurio I've updpated PR.
Fixed imports for python 3.8 and also reverted pydantic dependencies back. Feel free to review!

2022-11-08 06:10 UTC, arthurio reviewed
Thanks for the updates! Lets see if the tests pass and I'll probably merge/release it this week.

2022-11-08 06:10 UTC, arthurio commented on README.md
> +## Compatibility
👁️

2022-11-08 06:10 UTC, arthurio commented on docs/index.md
> +    city__in: Optional[List[str]]
I regret my decision when we started supporting 3.9 to update the docs with compatible code. I think that the documentation should show the syntax for the latest supported version. And if I have time to figure out how to show different code examples for different python versions then we can add these. WDYT?

2022-11-08 06:10 UTC, arthurio commented on examples/fastapi_filter_mongoengine.py
> +    return [{**user.to_mongo(), "address": user.address.to_mongo()} for user in query]
Good catch, I forgot about that nicety... Definitely not missing 3.8 😅

2022-11-08 08:21 UTC, 10ourto commented
@arthurio reverted everything related to docs examples back

2022-11-11 09:22 UTC, arthurio approved these changes

2022-11-11 09:22 UTC, arthurio commented
Thanks a lot @10ourto !

2022-11-11 09:43 UTC, merged

2022-11-15 10:10 UTC, 10ourto commented
@arthurio let me know please when next release is planned?
it could be nice to have new minor release with python 3.8 support