update codebase to support fastapi>=0.100.0 and pydantic>=2.0.0
arthurio/fastapi-filter pull request #447
Opened 2023-08-21 09:17 UTC by johnybx

Hi,
I updated codebase to support fastapi>=0.100.0 and pydantic>=2.0.0 ( this is breaking change ). I tried to keep same features and interface but when it comes to `with_prefix` function there were changes required. Currently with pydantic>=2.0.0 when you define attribute like in this example:
```python
        class MainFilter(BaseModel):
            name: str
            number_filter: Optional[NumberFilter] = FilterDepends(with_prefix("number_filter", NumberFilter))
```
you get error:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for FilterWrapper
  address
    Input should be a valid dictionary or instance of NumberFilter [type=model_type, input_value=FilterWrapper(...), input_type=FilterDepends.<locals>.FilterWrapper]
  For further information visit https://errors.pydantic.dev/2.2/v/model_type
```
The only workaround I found (currently) is to update `with_prefix` to generate the wrapped model and annotation with `PlainValidator`.

TODO:
- test with all supported python versions
- update documentation

2023-09-04 19:35 UTC, johnybx commented
I came up with different approach which does not introduce breaking changes to how  `with_prefix` is used. It would be nice if you could review the changes @arthurio. Thanks

2023-09-12 21:26 UTC, arthurio requested changes
That look really great, thank you so much for all your work!
I just have a few nits but we can ship it after that 🚀

2023-09-12 21:26 UTC, arthurio commented on fastapi_filter/base/filter.py
> +                    k: str
```suggestion
```

2023-09-12 21:26 UTC, arthurio commented on tests/test_mongoengine/test_order_by.py
> +@pytest.mark.usefixtures("users")
TIL, that's nice 👍🏻

2023-09-15 05:02 UTC, arthurio reviewed
Just that one last question so that we avoid confusion for people hitting that edge case, otherwise looks like it's ready to go! 👍🏻

2023-09-19 22:53 UTC, arthurio commented on fastapi_filter/base/filter.py
> +            # Do we need to handle Optional[Annotated[...]] ?
@johnybx Do you have time to make that change or do you want me to do it?

2023-09-22 12:10 UTC, johnybx commented
@arthurio sorry that it took so long but I just realized that `pending` label on comment does not mean that it is waiting for reviewer but rather that it is not submitted :facepalm:

2023-09-28 15:43 UTC, arthurio approved these changes
Let's do it! Thanks again for all the hard work, really appreciate it.

2023-09-28 15:43 UTC, merged